SELECT INITIALS, SUM(END_DATE - START_DATE +1) AS DAYS
FROM STO
LEFT JOIN EMPLOYEE ON STO.EMPLOYEE_ID = EMPLOYEE.ID
WHERE START_DATE > (CURRENT_DATE-365) AND START_DATE < CURRENT_DATE - 1
GROUP BY INITIALS
