SELECT START_DATE, END_DATE, COMMENT, EMPLOYEE.ID, EMPLOYEE.NAME, EMPLOYEE.INITIALS
FROM STO
LEFT JOIN EMPLOYEE
ON STO.EMPLOYEE_ID = EMPLOYEE.ID
WHERE $1 = EMPLOYEE.ID
  AND START_DATE >= CURRENT_DATE;
